Translating " Docs/error-decoder " to Arabic.
reactjs/ar.reactjs.org pull request #285
Opened 2020-12-03 13:56 UTC by E3saR33

2020-12-09 16:45 UTC, Aissaoui-Ahmed requested changes

2020-12-09 16:45 UTC, Aissaoui-Ahmed commented on content/docs/error-decoder.md
> +نوصي بشدة باستخدام إصدار التطوير محليًا عند تصحيح أخطاء تطبيقك نظرًا لأنه يتتبع معلومات تصحيح الأخطاء الإضافية ويوفر تحذيرات مفيدة حول المشكلات المحتملة في تطبيقاتك ، ولكن إذا واجهت استثناءً أثناء اس
```suggestion
نوصي بشدة باستخدام إصدار التطوير محليًا عند تصحيح أخطاء تطبيقك نظرًا لأنه يتتبع معلومات تصحيح الأخطاء الإضافية ويوفر تحذيرات مفيدة حول المشكلات المحتملة في تطبيقاتك ، ولكن إذا واجهت استثناءً أثناء استخدام بنية الإنتاج ، فستعيد هذه الصفحة تجميع النص الأصلي للخطأ.
```

2020-12-12 13:48 UTC, Aissaoui-Ahmed commented on content/docs/error-decoder.md
> +نوصي بشدة باستخدام إصدار التطوير محليًا عند تصحيح أخطاء تطبيقك نظرًا لأنه يتتبع معلومات تصحيح الأخطاء الإضافية ويوفر تحذيرات مفيدة حول المشكلات المحتملة في تطبيقاتك ، ولكن إذا واجهت استثناءً أثناء اس
/cc @E3saR33

2020-12-13 00:49 UTC, E3saR33 commented on content/docs/error-decoder.md
> +نوصي بشدة باستخدام إصدار التطوير محليًا عند تصحيح أخطاء تطبيقك نظرًا لأنه يتتبع معلومات تصحيح الأخطاء الإضافية ويوفر تحذيرات مفيدة حول المشكلات المحتملة في تطبيقاتك ، ولكن إذا واجهت استثناءً أثناء اس
Thanks. ✨❤

2020-12-13 00:58 UTC, merged