Fix typos & review translation
reactjs/ar.reactjs.org pull request #288
Opened 2020-12-19 15:10 UTC by atefBB

The translation need re-`review` !

2020-12-19 15:10 UTC, atefBB commented
@3imed-jaberi @Aissaoui-Ahmed Need your reviews

2020-12-20 18:57 UTC, Aissaoui-Ahmed requested changes
Remove double space

2020-12-20 18:57 UTC, Aissaoui-Ahmed commented on content/docs/thinking-in-react.md
> +مع نهاية هذه الخطوة، سيكون لديك مكتبة من المكونات القابلة لإعادة الاستخدام (reusable) التي تقوم بتصيير نموذج البيانات، المكونات ستحتوي فقط على دالات (`render()`) حيث أن هذه نسخة ثابتة من تطبيقك، المك
```suggestion
مع نهاية هذه الخطوة، سيكون لديك مكتبة من المكونات القابلة لإعادة الاستخدام (reusable) التي تقوم بتصيير نموذج البيانات، المكونات ستحتوي فقط على دالات (`render()`) حيث أن هذه نسخة ثابتة من تطبيقك، المكون بأعلى التسلسل الهرمي (`FilterableProductTable`) سيحصل علي نموذج البيانات بصفته خاصية (prop)، إذا قمت بعمل تغيير في نموذج البيانات وقمت باستدعاء الدالة (`ReactDOM.render()`) مرة أخرى فإن واجهة المستخدم سيتم تحديثها، من السهل رؤية كيف يتم تحديث واجهة المستخدم وأين تحدث التغييرات فلا يوجد شيء معقد، طريقة تدفق البيانات في اتجاه واحد (**one-way data flow**) الخاصة بـ (React) وتدعي أيضاَ بـ (*one-way binding*) تحافظ على كل شيء سريع ووحدة (modular) واحدة.
```

2020-12-20 18:57 UTC, Aissaoui-Ahmed commented on content/docs/thinking-in-react.md
> +رائع، لقد قررنا أن الحالة ستكون في المكون `FilterableProductTable`، أولاَ أضف (instance property) `this.state = {filterText: '', inStockOnly: false}` لل `constructor` للمكون `FilterableProductTable`
```suggestion
رائع، لقد قررنا أن الحالة ستكون في المكون `FilterableProductTable`، أولاَ أضف (instance property) `this.state = {filterText: '', inStockOnly: false}` لل `constructor` للمكون `FilterableProductTable` 
 لتكون الحالة الإبتدائية للتطبيق ثم مرر الحالتين `filterText` و `inStockOnly` للمكونين `ProductTable` و `SearchBar` بصفتها خاصيات (props) وفي النهاية، استخدم هذه الخاصيات (props) لتنقيح صفوف المنتجات في المكون `ProductTable` وضع القيم للـ (form fields) في المكون `SearchBar`.
```

2020-12-20 18:57 UTC, Aissaoui-Ahmed commented on content/docs/thinking-in-react.md
> +##  الخطوة الثالثة: تحديد الحد الأدنى (ولكن المكتمل) الممثل لحالة واجهة المستخدم{#step-3-identify-the-minimal-but-complete-representation-of-ui-state}
```suggestion
## الخطوة الثالثة: تحديد الحد الأدنى (ولكن المكتمل) الممثل لحالة واجهة المستخدم{#step-3-identify-the-minimal-but-complete-representation-of-ui-state}
```

2020-12-20 18:57 UTC, Aissaoui-Ahmed commented on content/docs/thinking-in-react.md
> +ولكن كيف تعرف ما يجب أن تحدده بصفته مكونا؟ فقط استخدم نفس الأساليب أثناء أخذ قرار بإنشاء دالة (Function) أو كائن (Object) جديد، أسلوب "مبدأ المسئولية الأحادية" هو مثال على ذلك [single responsibility
```suggestion
ولكن كيف تعرف ما يجب أن تحدده بصفته مكونا؟ فقط استخدم نفس الأساليب أثناء أخذ قرار بإنشاء دالة (Function) أو كائن (Object) جديد، أسلوب "مبدأ المسئولية الأحادية" هو مثال على ذلك [مبدأ المهمة الواحدة](https://ar.wikipedia.org/wiki/%D9%85%D8%A8%D8%AF%D8%A3_%D8%A7%D9%84%D9%85%D9%87%D9%85%D8%A9_%D8%A7%D9%84%D9%88%D8%A7%D8%AD%D8%AF%D8%A9) وهي أن المكون (component) بشكل مثالي يجب أن يكون مسئولا عن فعل شيء واحد فقط، وإذا بدأ في التنامي يجب تقسيمه إلى مكونات فرعية (subcomponent) أصغر.
```

2020-12-20 19:37 UTC, atefBB commented
@Aissaoui-Ahmed DONE!

2020-12-20 20:15 UTC, Aissaoui-Ahmed approved these changes

2020-12-20 20:16 UTC, merged