Update team.md
reactjs/ar.reactjs.org pull request #297
Opened 2021-02-04 10:03 UTC by E3saR33

I've translated team.md to Arabic.

2021-02-04 10:06 UTC, E3saR33 commented on content/community/team.md
> -title: Team
Page title in Arabic : الفريق

2021-02-04 10:08 UTC, Aissaoui-Ahmed commented on content/community/team.md
> +نود أن نقدم شكر خاص ل [توم أوتشينو](https://github.com/tomocchino) و [آدم وولف](https://github.com/wolffiex) على مساعدتهم و توجيههم على مر السنين.
```suggestion
نود أن نقدم شكر خاص ل [Tom Occhino](https://github.com/tomocchino) و [Adam Wolff](https://github.com/wolffiex) على مساعدتهم و توجيههم على مر السنين.
```

2021-02-04 10:12 UTC, E3saR33 commented on content/community/team.md
> +نود أن نقدم شكر خاص ل [توم أوتشينو](https://github.com/tomocchino) و [آدم وولف](https://github.com/wolffiex) على مساعدتهم و توجيههم على مر السنين.
👏🏻👍🏻

2021-02-13 01:05 UTC, Aissaoui-Ahmed requested changes

2021-02-13 01:05 UTC, Aissaoui-Ahmed commented on content/community/team.md
> +هو أيضاً يعتني بألطف قطة في العالم
??

2021-02-15 19:04 UTC, closed without merging